app/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Agency, Customer, SearchHistory, Country, Airport, City, Airline, Cabin
from . import db
import requests
import json
from datetime import datetime, timedelta
import pytz

from cryptography.fernet import Fernet
from collections import defaultdict
views = Blueprint('views', __name__)


# Secret key for encryption and decryption
SECRET_KEY = "your_secret_key_here"


@views.route('/get_airport_suggestions', methods=['GET'])
def get_airport_suggestions():
    search = request.args.get('search', '').strip().lower()
    page = int(request.args.get('page', 1))  
    per_page = 50 
    
    offset = (page - 1) * per_page
    
    airports = db.session.query(Airport, Country.name).join(
        Country, Airport.country_code == Country.code
    ).filter(
        db.or_(
            Airport.name.ilike(f'%{search}%') 
            #Airport.iata_code.ilike(f'%{search}'), 
            #Country.name.ilike(f'%{search}%')
        )
    ).limit(per_page).offset(offset).all()

    airport_suggestions = [{'name': airport.name, 'iata_code': airport.iata_code, 'country_name': country_name}
                           for airport, country_name in airports]
    print(airport_suggestions)
    return jsonify({'airports': airport_suggestions})

def convert_and_format_time(raw_time):
    user_timezone_offset =6
    
    time_parts = raw_time.split('+') if '+' in raw_time else raw_time.split('-')
    if len(time_parts) != 2:
        raise ValueError("Invalid time format")

    time_str = time_parts[0]
    sign = '+' if '+' in raw_time else '-'
    offset_str = time_parts[1]

    parsed_time = datetime.strptime(time_str, '%H:%M:%S')

    offset_hours = int(offset_str.split(':')[0])
    offset_minutes = int(offset_str.split(':')[1])

    if sign == '+':
        user_offset_minutes = user_timezone_offset * 60
        offset_difference_minutes = user_offset_minutes - (offset_hours * 60 + offset_minutes)
    elif sign == '-':
        user_offset_minutes = user_timezone_offset * 60
        offset_difference_minutes = user_offset_minutes + (offset_hours * 60 + offset_minutes)
    else:
        raise ValueError("Invalid sign in the offset")


    adjusted_time = parsed_time + timedelta(minutes=offset_difference_minutes)
    formatted_time = adjusted_time.strftime('%I:%M %p')

    return formatted_time

def get_airport_name(departure_airport_iata):
    departure_airport = Airport.query.filter_by(iata_code=departure_airport_iata).first()
    departure_airport_name = departure_airport.name if departure_airport else departure_airport_iata
    return departure_airport_name

def get_city_name(departure_city_iata):
    departure_city = City.query.filter_by(city_code=departure_city_iata).first()
    departure_city_name = departure_city.name if departure_city else departure_city_iata
    return departure_city_name

def get_country_name(departure_country_code):
    departure_country = Country.query.filter_by(code=departure_country_code).first()
    departure_country_name = departure_country.name if departure_country else departure_country_code

    return departure_country_name

def format_date(input_date):
    
    parsed_date = datetime.strptime(input_date, '%Y-%m-%d')
    formatted_date = parsed_date.strftime('%a, %d %b %y')

    return formatted_date

def convert_duration(minutes):
    if minutes < 0:
        raise ValueError("Duration cannot be negative")

    days = minutes // 1440
    hours = (minutes % 1440) // 60
    minutes = minutes % 60

    duration_str = ""

    if days > 0:
        duration_str += f"{days} day{'s' if days > 1 else ''}, "

    if hours > 0:
        duration_str += f"{hours} hour{'s' if hours > 1 else ''}, "

    if minutes > 0:
        duration_str += f"{minutes} minute{'s' if minutes > 1 else ''}"

    if duration_str.endswith(", "):
        duration_str = duration_str[:-2]

    return duration_str

def get_airline_name(airline_code):
    airline = Airline.query.filter_by(AirlineCode=airline_code).first()
    if airline:
        return airline.AlternativeBusinessName
    else:
        return None

def get_cabin_name(cabin_code):
    cabin = Cabin.query.filter_by(cabin_code=cabin_code).first()
    if cabin:
        return cabin.name
    else:
        return None



@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route('/viewprofile')
@login_required
def viewprofile():
    return render_template("viewprofile.html", user=current_user)


@views.route('/view_flight/<int:search_id>', methods=['GET'])
@login_required
def view_flight(search_id):
    search_history = SearchHistory.query.filter_by(search_id=search_id, agency_id=current_user.agency_id).first()
    if search_history:
        flight_schedules = json.loads(search_history.response)
        flight_count = len(flight_schedules)
        return render_template('flights.html', flight_schedules=flight_schedules, flight_count=flight_count)
    else:
        error_message = "Search history not found."
        return render_template('flights.html', error_message=error_message)
    

@views.route('/flights', methods=['GET', 'POST'])
@login_required
def flights():
    if request.method == 'POST':
        iata_from = request.form.get('iataFrom')
        iata_to = request.form.get('iataTo')
        journey_date = request.form.get('journey_date')
        
        adult = int(request.form.get('adult'))
        child = int(request.form.get('child'))
        infant = int(request.form.get('infant'))
        total_passenger = int(adult+child+infant)
        
        cab = request.form.get('select_cabin')
        if cab == "Economy":
            cabin= "Y"
        elif cab == "Business":
            cabin="C"
        elif cab == "First Class":
            cabin="F"
            
        sabre_api_url = f'https://api.cert.platform.sabre.com/v4/offers/shop'

        headers = {
            "Authorization": f"Bearer T1RLAQJl7PCx+uMQW4bTBqGf3quNgeakNF5yZLQApxWMsbqqkRB5YZDJs8L3gvh4klQQ78VyAADgpra6XonPFWIBBBf23IG7pMF3OrOhEwnlkLg3GUiDsNrw4KeRkgpai/kFp+wDBPkwzge9pHlFn2DDd7eDrZ7HCR6E27NA5lItrZwsFZvQsv02YTeMfW64rYpWiB2sss7PQSo5s1up63qojb+DeWF3lYIEc6TEKC04W1qSf18V/T5g6NmmFh4WTxIG0vpLTLJsGbU+5fVOT0ZuZ/wgqw+impb5kjBj+kkQf4RRr3saLbCnn2lUjMZrIuJNEgjTDsnIY6ceHZ5GRp2aRIaHo6AoflpDOkAjHqKfQYtkxHcUHq8*"
        }
        
        # Initialize an empty list to store passenger data
        passenger_data = []

        for _ in range(adult):
            passenger = {
                "Code": "ADT",  
                "Quantity": 1 
            }
            passenger_data.append(passenger)
    
    
        for _ in range(child):
            passenger = {
                "Code": "C07",  
                "Quantity": 1 
            }
            passenger_data.append(passenger)
    

        for _ in range(infant):
            passenger = {
                "Code": "INY",  
                "Quantity": 1 
            }
            passenger_data.append(passenger)
            
        #print(passenger_data)
        
        request_body = {
            "OTA_AirLowFareSearchRQ": {
                "ResponseType": "GIR",
                "Version": "4",
                "AvailableFlightsOnly": True,
                "POS": {
                    "Source": [
                        {
                            "PseudoCityCode": "40OK",
                            "RequestorID": {
                                "Type": "1",
                                "ID": "1",
                                "CompanyName": {
                                    "Code": "TN"
                                }
                            }
                        }
                    ]
                },
                "OriginDestinationInformation": [
                    {
                        "RPH": "1",
                        "DepartureDateTime": journey_date+"T00:00:00",
                        "OriginLocation": {
                            "LocationCode": iata_from
                        },
                        "DestinationLocation": {
                            "LocationCode": iata_to
                        }
                    }
                ],
                "TravelerInfoSummary": {
                    "AirTravelerAvail": [
                        {
                            "PassengerTypeQuantity": passenger_data
                        }
                    ]
                },
                "TPA_Extensions": {
                    "IntelliSellTransaction": {
                        "RequestType": {
                            "Name": "50ITINS"
                        }
                    }
                }
            }
        }


        try:

            response = requests.post(sabre_api_url, headers=headers, json=request_body)
            response.raise_for_status()

            response_data = response.json()

            messages = response_data["groupedItineraryResponse"]["messages"]
            statistics = response_data["groupedItineraryResponse"]["statistics"]
            schedule_descs = response_data["groupedItineraryResponse"]["scheduleDescs"]
            tax_descs = response_data["groupedItineraryResponse"]["taxDescs"]
            tax_summary_descs = response_data["groupedItineraryResponse"]["taxSummaryDescs"]
            fare_component_descs = response_data["groupedItineraryResponse"]["fareComponentDescs"]
            baggage_allowance_descs = response_data["groupedItineraryResponse"]["baggageAllowanceDescs"]
            leg_descs = response_data["groupedItineraryResponse"]["legDescs"]
            itinerary_groups = response_data["groupedItineraryResponse"]["itineraryGroups"]

            departure_date = response_data["groupedItineraryResponse"]["itineraryGroups"][0]["groupDescription"]["legDescriptions"][0]["departureDate"]

app/templates/addemployees.html
{% extends "base.html" %}
{% block title %}Add Employees{% endblock %}
{% block base %}
{% block header %}Add Employees Information{% endblock %}
<div class="row mb-8 mt-5 ">
    <div class="col-xl-2 col-lg-2 "></div>
    <div class="col-xl-8 col-lg-8 col-md-12 col-12">
        <!-- card -->
        <div class="card">
            <!-- card body -->
            <div class="card-body my-4 mx-4">

                <div class="row align-items-center mb-4">
                    <div class="col-md-3 mb-3 mb-md-0">
                        <h5 class="mb-0">Avatar</h5>
                    </div>
                    <div class="col-md-9">
                        <div class="d-flex align-items-center mb-4">
                            <div>
                                <img class="image  avatar avatar-lg rounded-circle"
                                    src="https://i.ibb.co/P63D45j/face2.jpg" alt="Image">
                            </div>

                            <div class="file-upload btn btn-outline-white ms-4">
                                <input type="file" class="file-input opacity-0">Upload Photo
                            </div>
                        </div>

                    </div>
                </div>
                <div>

                    <div class="mb-4">
                        <h4 class="mb-1">Basic information</h4>

                    </div>
                    <form>


                        <div class="mb-3 row">
                            <label for="fullName" class="col-sm-4 col-form-label
                    form-label">Full name</label>
                            <div class="col-sm-4 mb-3 mb-lg-0">
                                <input type="text" class="form-control" placeholder="First name" id="fullName" required>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Last name" id="lastName" required>
                            </div>
                        </div>

                        <div class="mb-3 row">
                            <label for="email" class="col-sm-4 col-form-label
                    form-label">Email</label>
                            <div class="col-md-8 col-12">
                                <input type="email" class="form-control" placeholder="Email" id="email" required>
                            </div>
                        </div>

                        <div class="mb-3 row">
                            <label for="phone" class="col-sm-4 col-form-label
                    form-label">Phone </label>
                            <div class="col-md-8 col-12">
                                <input type="text" class="form-control" placeholder="Phone" id="phone" required>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="gender" class="col-sm-4 col-form-label
                                form-label">Gender</label>

                            <div class="col-md-8 col-12">
                                <select class="form-select" id="gender">
                                    <option selected>Male</option>
                                    <option value="1">Female</option>
                                    <option value="2">Other</option>
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="address" class="col-sm-4 col-form-label
                    form-label">Address</label>


                            <div class="col-md-8 col-12">
                                <input type="text" class="form-control" placeholder="586 Wyman Village" id="address"
                                    required>
                            </div>
                        </div>

                        <div class="mb-3 row">
                            <label for="zip" class="col-sm-4
                    col-form-label form-label">Zip Code</label>
                            <div class="col-md-8 col-12">
                                <input type="text" class="form-control" placeholder="12345" id="zip"
                                    required>
                            </div>
                        </div>

                        <div class="row align-items-center">
                            <label for="nid" class="col-sm-4 col-form-label
                    form-label">National ID </label>

                            <div class="col-md-8 col-12">
                                <input type="text" class="form-control" placeholder="0123456789" id="nid" required>
                            </div>
                            <div class="offset-md-4 col-md-8 mt-4">
                                <button type="submit" class="btn btn-primary"> Save
                                    Information </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <div class="col-xl-2 col-lg-2 "></div>
</div>
{% endblock %}

app/templates/flightshistory.html
{% extends "base.html" %}
{% block title %}Flights History{% endblock %}
{% block base %}
{% block header %}Flights History{% endblock %}

<div class="row mt-4">
    <div class="col-lg-2 col-xl-2"></div>
    <!-- col -->
    <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12">
        <!-- card -->
        <div class="card">
            <!-- table -->
            <div class="table-responsive">
                <table class="table mb-0 text-nowrap table-centered">
                    <thead class="table-light">
                        <tr>
                            <th>History ID</th>
                            <th>Form</th>
                            <th>To</th>
                            <th>Date</th>
                            
                          
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                1
                            </td>
                            <td>
                                Dhaka
                            </td>
                            <td>
                                Dubai
                            </td>
                            <td>
                                09-30-2023
                            </td>
                           
                        </tr>



                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-xl-2"></div>
</div>

{% endblock %}

app/templates/hotelsbookingserach.html
{% extends "base.html" %}
{% block title %}Hotels Booking History{% endblock %}
{% block base %}
{% block header %}Hotels Booking History{% endblock %}
<div class="row justify-content-md-between mb-4 mb-xl-0 mt-4">

    <div class="col-xl-2 col-lg-4 col-md-6 col-12">
 
        <div class="mb-lg-4 mb-2">
            <input type="search" class="form-control" placeholder="Search by booking history">
        </div>
    </div>
</div>

<div class="row">

    <div class="col-12">

        <div class="card">

            <div class="table-responsive">
                <table class="table mb-0 text-nowrap table-centered">
                    <thead class="table-light">
                        <tr>
                            <th>Booking ID</th>
                            <th>Name</th>
                            <th>Hotels</th>
                            <th>Location</th>
                            <th>Date Time</th>
                            <th>Price</th>
                            <th>Commission</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>

                                <div class="ms-3">
                                    <h4 class="mb-0 fs-5"><a href="#!" class="text-inherit">012</a></h4>
                                </div>

                            </td>
                            <td>
                                Saif Sunny
                            </td>
                            <td>
                                Hotel 71
                            </td>
                            <td>
                                USA
                            </td>
                            <td>
                                09-30-2023 10.00 am
                            </td>
                            <td>
                                $500.00
                            </td>
                            <td>
                                $2.00
                            </td>
                            <td>
                                <span class="badge badge-success-soft p-2">Complete</span>
                            </td>
                        </tr>
                        <tr>
                            <td>

                                <div class="ms-3">
                                    <h4 class="mb-0 fs-5"><a href="#!" class="text-inherit">012</a></h4>
                                </div>

                            </td>
                            <td>
                                Saif Sunny
                            </td>
                            <td>
                                Dusai Resort and Spa
                            </td>
                            <td>
                                USA
                            </td>
                            <td>
                                09-30-2023 10.00 am
                            </td>
                            <td>
                                $500.00
                            </td>
                            <td>
                                $2.00
                            </td>
                            <td>
                                <span class="badge badge-danger-soft p-2">Cancelled</span>
                            </td>
                        </tr>
                        <tr>
                            <td>

                                <div class="ms-3">
                                    <h4 class="mb-0 fs-5"><a href="#!" class="text-inherit">012</a></h4>
                                </div>

                            </td>
                            <td>
                                Saif Sunny
                            </td>
                            <td>
                                Hotel Dhaka Garden Inn
                            </td>
                            <td>
                                USA
                            </td>
                            <td>
                                09-30-2023 10.00 am
                            </td>
                            <td>
                                $500.00
                            </td>
                            <td>
                                $2.00
                            </td>
                            <td>
                                <span class="badge badge-warning-soft p-2">Pending</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/hotelshistory.html
{% extends "base.html" %}
{% block title %}Hotels History{% endblock %}
{% block base %}
{% block header %}Hotels History{% endblock %}

<div class="row mt-4">
    <div class="col-lg-2 col-xl-2"></div>
    <!-- col -->
    <div class="col-lg-8 col-xl-8 col-md-12 col-sm-12">
        <!-- card -->
        <div class="card">
            <!-- table -->
            <div class="table-responsive">
                <table class="table mb-0 text-nowrap table-centered">
                    <thead class="table-light">
                        <tr>
                            <th>History ID</th>
                            <th>Location</th>
                            <th>Date</th>
                            
                          
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                1
                            </td>
                            <td>
                                Dubai
                            </td>
                            <td>
                                09-30-2023
                            </td>
                           
                        </tr>



                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-xl-2"></div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css"
        integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/7.2.96/css/materialdesignicons.min.css"
        integrity="sha512-LX0YV/MWBEn2dwXCYgQHrpa9HJkwB+S+bnBpifSOTO1No27TqNMKYoAn6ff2FBh03THAzAiiCwQ+aPX+/Qt/Ow=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplebar/6.2.5/simplebar.css"
        integrity="sha512-08T4cwCCcdn+1J5Kne6cRZwBFGo11KAc8b9dk6vDFkdscSz9L/rVUGl+kbIT8zQbBGqxkYwjz+HoZNp6B8bA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- main css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Travel360-{% block title %}Base{% endblock %}</title>
</head>

<body>

    {% block base %} {% endblock %}


</body>

</html>

app/templates/search_history.html
{% extends "layout/dashboard.html" %}

{% block dashboard %}
<div class="row">
    <div class="col-sm-12 ">
        <div class="card ms-2 me-2">
            <div class="card-body">
                <p class="card-title mb-0">Search History</p>

                <div class="table-responsive">
                    <table class="table table-striped table-borderless text-center">
                        <thead>
                            <tr>
                                <th>History ID</th>
                                <th>From</th>
                                <th>TO</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for search_history in search_history %}
                            <tr>
                                <td><a href="{{ url_for('views.view_flight', search_id=search_history.search_id) }}">{{search_history.search_id}}</a></td>
                                <td>{{search_history.from_location}}</td>
                                <td>{{search_history.to_location}}</td>
                                <td>{{search_history.search_date_time}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer ms-2 me-2 col-md-12 position-absolute  top-100">
        <p class=" text-center ">Copyright © 2023.
            All rights reserved.</p>
    </footer>
</div>
{% endblock %}

app/templates/signup.html
{% extends "layout/base.html" %} {% block title %}Register{% endblock %}

{% block content %}
<div class="container-scroller">
  <div class="container-fluid page-body-wrapper full-page-wrapper">
    <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
      <div class="row flex-grow">
        <div class="col-lg-6 d-flex align-items-center justify-content-center">
          <div class="auth-form-transparent text-left p-3">
            <div class="brand-logo">
              <h1 class="text-info">Travel360</h1>
            </div>
            <h4>New here?</h4>
            <h6 class="font-weight-light">Join us today! It takes only few steps</h6>
            <form class="pt-3" method="POST">
              <div class="form-group">
                <label>Agency Name</label>
                <div class="input-group">
                  <div class="input-group-prepend bg-transparent">
                    <span class="input-group-text bg-transparent border-right-0">
                      <i class="ti-user text-primary"></i>
                    </span>
                  </div>
                  <input type="text" class="form-control form-control-lg border-left-0" placeholder="Agency Name"
                    name="agency_name" required>
                </div>
              </div>
              <div class="form-group">
                <label>Email</label>
                <div class="input-group">
                  <div class="input-group-prepend bg-transparent">
                    <span class="input-group-text bg-transparent border-right-0">
                      <i class="ti-email text-primary"></i>
                    </span>
                  </div>
                  <input type="email" class="form-control form-control-lg border-left-0" placeholder="Email"
                    name="email" required>
                </div>
              </div>
              <div class="form-group">
                <label> Password</label>
                <div class="input-group">
                  <div class="input-group-prepend bg-transparent">
                    <span class="input-group-text bg-transparent border-right-0">
                      <i class="ti-lock text-primary"></i>
                    </span>
                  </div>
                  <input type="password" class="form-control form-control-lg border-left-0" id="exampleInputPassword"
                    placeholder="Password" name="password">
                </div>
              </div>
              <div class="form-group">
                <label>Confirm Password</label>
                <div class="input-group">
                  <div class="input-group-prepend bg-transparent">
                    <span class="input-group-text bg-transparent border-right-0">
                      <i class="ti-lock text-primary"></i>
                    </span>
                  </div>
                  <input type="password" class="form-control form-control-lg border-left-0" id="exampleInputPassword"
                    placeholder="Password" name="password-repeat">
                </div>
              </div>
              <div class="mt-3">
                <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">SIGN
                  UP</button>
              </div>
              <div class="mb-2 d-flex mt-3">
                <button type="button" class="btn btn-facebook auth-form-btn flex-grow me-1">
                  <i class="ti-facebook me-2"></i>Facebook
                </button>
                <button type="button" class="btn btn-google auth-form-btn flex-grow ms-1">
                  <i class="ti-google me-2"></i>Google
                </button>
              </div>
              <div class="text-center mt-4 font-weight-light">
                Already have an account? <a href="{{ url_for('auth.login')}}" class="text-primary">Login</a>
              </div>
            </form>
          </div>
        </div>
        <div class="col-lg-6 d-none d-lg-flex flex-row" style="background-image: url('https://i.ibb.co/ccG08r3/signup.jpg');
            height: 100vh;opacity: 80%; ">
          <p class="text-black font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2023 All
            rights reserved.</p>
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
  </div>
  <!-- page-body-wrapper ends -->
</div>
{% endblock %}